# Generated by Django 5.2.15 on 2026-08-17 18:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=160)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('tanda', models.CharField(choices=[('MATUTINA', 'Matutina'), ('VESPERTINA', 'Vespertina'), ('NOCTURNA', 'Nocturna'), ('MIXTA', 'Mixta')], default='MATUTINA', max_length=12)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('fecha_ingreso', models.DateField()),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados', 'ordering': ('nombre',)},
        ),
    ]
