# Generated by Django 5.2.15 on 2026-08-17 18:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('articulos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_renta', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('PARCIAL', 'Parcialmente devuelta'), ('DEVUELTA', 'Devuelta'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABIERTA', max_length=12)),
                ('comentarios', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentas', to='clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentas', to='empleados.empleado')),
            ],
            options={'verbose_name': 'Renta', 'verbose_name_plural': 'Rentas', 'ordering': ('-fecha_renta',)},
        ),
        migrations.CreateModel(
            name='DetalleRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dias_renta', models.PositiveSmallIntegerField(default=1)),
                ('fecha_esperada_devolucion', models.DateTimeField(db_index=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recargo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('inventario_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_renta', to='articulos.inventarioitem')),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rentas.renta')),
            ],
            options={'verbose_name': 'Detalle de renta', 'verbose_name_plural': 'Detalles de renta', 'ordering': ('renta_id', 'id'), 'constraints': [models.UniqueConstraint(fields=('renta', 'inventario_item'), name='uq_renta_inventario_item')]},
        ),
    ]
