# Generated by Django 5.2.15 on 2026-08-17 18:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [('catalogos', '0001_initial')]
    operations = [
        migrations.CreateModel(
            name='PersonaElenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=160)),
                ('nombre_artistico', models.CharField(blank=True, max_length=160)),
            ],
            options={'verbose_name': 'Persona de elenco', 'verbose_name_plural': 'Personas de elenco', 'ordering': ('nombre',)},
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('titulo', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('monto_renta_dia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dias_renta', models.PositiveSmallIntegerField(default=1)),
                ('monto_entrega_tardia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('generos', models.ManyToManyField(blank=True, related_name='articulos', to='catalogos.genero')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='catalogos.idioma')),
                ('tipo_articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='catalogos.tipoarticulo')),
            ],
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos', 'ordering': ('titulo',)},
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RENTADO', 'Rentado'), ('MANTENIMIENTO', 'Mantenimiento'), ('RETIRADO', 'Retirado')], db_index=True, default='DISPONIBLE', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='articulos.articulo')),
            ],
            options={'verbose_name': 'Unidad de inventario', 'verbose_name_plural': 'Unidades de inventario', 'ordering': ('codigo',)},
        ),
        migrations.CreateModel(
            name='ArticuloElenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('ACTOR', 'Actor/Actriz'), ('DIRECTOR', 'Director/a'), ('PRODUCTOR', 'Productor/a'), ('AUTOR', 'Autor/a'), ('INTERPRETE', 'Intérprete'), ('OTRO', 'Otro')], max_length=20)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_elenco', to='articulos.articulo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to='articulos.personaelenco')),
            ],
            options={'verbose_name': 'Participación de elenco', 'verbose_name_plural': 'Participaciones de elenco', 'ordering': ('articulo__titulo', 'persona__nombre', 'rol')},
        ),
        migrations.AddField(model_name='articulo', name='elenco', field=models.ManyToManyField(blank=True, related_name='articulos', through='articulos.ArticuloElenco', to='articulos.personaelenco')),
        migrations.AddConstraint(model_name='articuloelenco', constraint=models.UniqueConstraint(fields=('articulo', 'persona', 'rol'), name='uq_articulo_persona_rol')),
    ]
