# Generated by Django 5.2.15 on 2026-08-17 18:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=160)),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Cédula/RNC')),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Persona física'), ('JURIDICA', 'Persona jurídica')], default='FISICA', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes', 'ordering': ('nombre',)},
        ),
    ]
