# Generated by Django 5.2.15 on 2026-08-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Genero', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('creado_en', models.DateTimeField(auto_now_add=True)), ('actualizado_en', models.DateTimeField(auto_now=True)), ('activo', models.BooleanField(db_index=True, default=True)), ('descripcion', models.CharField(max_length=120, unique=True))], options={'verbose_name': 'Género', 'verbose_name_plural': 'Géneros', 'ordering': ('descripcion',), 'abstract': False}),
        migrations.CreateModel(name='Idioma', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('creado_en', models.DateTimeField(auto_now_add=True)), ('actualizado_en', models.DateTimeField(auto_now=True)), ('activo', models.BooleanField(db_index=True, default=True)), ('descripcion', models.CharField(max_length=120, unique=True))], options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas', 'ordering': ('descripcion',), 'abstract': False}),
        migrations.CreateModel(name='TipoArticulo', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('creado_en', models.DateTimeField(auto_now_add=True)), ('actualizado_en', models.DateTimeField(auto_now=True)), ('activo', models.BooleanField(db_index=True, default=True)), ('descripcion', models.CharField(max_length=120, unique=True))], options={'verbose_name': 'Tipo de artículo', 'verbose_name_plural': 'Tipos de artículos', 'ordering': ('descripcion',), 'abstract': False}),
    ]
